apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations
  annotations:
    # "helm.sh/hook": pre-install,pre-upgrade # Rulează înainte de deployment-ul Kong
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: kong-migrations
        image: kong:3.8
        command: ["kong", "migrations", "bootstrap"]
        env:
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: "postgres" # Numele serviciului creat mai sus
        - name: KONG_PG_DATABASE
          value: "kong" # Numele serviciului creat mai sus
        - name: KONG_PG_USER
          value: "kong"
        - name: KONG_PG_PASSWORD
          value: "kong"
