apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ms-kong.fullname" . }}-mysql-pvc
  namespace: default
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# ElasticSearch Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ms-kong.fullname" . }}-es-pvc
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - {{ .Values.elasticsearch.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.elasticsearch.storage.size }}

---
# RabbitMQ Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Keycloak Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Kong Persistent Volume Claim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: {{ .Values.global.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi      