apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  DB_PASSWORD: dGVzdHBhc3M=
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ms-kong.fullname" . }}-elk-secrets
  namespace: default
type: Opaque
data:
  # echo -n 'passwOrd' | base64
  elastic_password: cGFzc3dPcmQ=
  # echo -n 'passwOrd' | base64
  kibana_password: cGFzc3dPcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ms-kong.fullname" . }}-keycloak-secret
type: Opaque
data:
  adminUser: YWRtaW4=              # base64(admin)
  adminPassword: YWRtaW4=          # base64(admin)
  clientSecret: bXktc2VjcmV0LWtleWNsb2Fr # base64(bXktc2VjcmV0LWtleWNsb2Fr)